---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/consul-k8s --version
    register: consul_k8s_test_output
  - name: consul-k8s --version
    debug:
      msg: '{{ consul_k8s_test_output.stderr }}'
