---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for existing install
  become: yes
  stat:
    path: '{{ consul_k8s_install_dir }}'
  changed_when: False
  register: consul_k8s_binary
- when: not consul_k8s_binary.stat.exists
  block:
    - name: download consul-k8s...
      become: yes
      become_user: root
      get_url:
        url: '{{ consul_k8s_url }}'
        dest: /tmp/{{ consul_k8s_archive }}
        checksum: '{{ consul_k8s_checksum }}'
        mode: 0644
    - name: mkdir for install
      become: yes
      become_user: root
      file:
        path: '{{ consul_k8s_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ consul_k8s_archive }}
        dest: '{{ consul_k8s_install_dir }}'
        creates: '{{ consul_k8s_install_exe }}'
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{ consul_k8s_archive }}
        state: absent
- name: link...
  become: yes
  become_user: root
  file:
    src: '{{ consul_k8s_install_exe }}'
    dest: '{{ consul_k8s_link }}'
    state: link
