---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for existing install in {{ consul_k8s_install_dir }}
  become: yes
  stat:
    path: '{{ consul_k8s_install_dir }}'
  changed_when: False
  register: consul_k8s_binary
- when: not consul_k8s_binary.stat.exists
  block:
    - name: download {{ consul_k8s_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ consul_k8s_url }}'
        dest: '{{ consul_k8s_tmp_archive }}'
        checksum: '{{ consul_k8s_checksum }}'
        mode: 0644
    - name: mkdir {{ consul_k8s_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ consul_k8s_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ consul_k8s_tmp_archive }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ consul_k8s_tmp_archive }}'
        dest: '{{ consul_k8s_install_dir }}'
        creates: '{{ consul_k8s_install_exe }}'
  always:
    - name: rm {{ consul_k8s_tmp_archive }}
      become: yes
      become_user: root
      file:
        path: '{{ consul_k8s_tmp_archive }}'
        state: absent
- name: linking {{ consul_k8s_link }} to {{ consul_k8s_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ consul_k8s_install_exe }}'
    dest: '{{ consul_k8s_link }}'
    state: link
